/*
 * adc_MCP3564R_config.h
 *
 *  Created on: Apr 21, 2026
 *      Author: paul
 */

#ifndef ADC_MCP3564R_CONFIG_H_
#define ADC_MCP3564R_CONFIG_H_

/**********************************************************************************************************************/
/* PREPROCESSOR DEFINES ***********************************************************************************************/
/**********************************************************************************************************************/
/*
 * We can optionally use a standard delay on each task loop, to enforce a limit on how fast the task will run,
 * and indirectly how much of the time it sleeps.
 */
#define ADC_TASK_DELAY_MSEC 1

/*
 * How long to wait for the conversion complete interrupt. Specifying 1ms does not guarantee waiting one whole
 * msec,
 */
#define ADC_CONV_COMPLETE_TIMEOUT_MSEC 2

/*
 * How long to wait for SPI transactions to complete (determined by our interrupt callback, either using the HAL
 * SPI interrupt APIs or DMA APIs. In our ADC task we get better performance (lower latency) using the interrupt
 * APIs, probably because the overhead of setting up the DMA transfers is excessive compared to the small
 * transaction sizes.
 */
#define ADC_HAL_SPI_TIMEOUT_MSEC 2

/*
 * Options to configure the ADC functionality:
 *
 * MCP3564_USE_EXT_CLOCK: the micro places a clock signal on a PWM output pin and the ADC should use this for
 * clocking. Otherwise, use the internal clock (which can have a lot of variation; it is only specified to
 * be between 3.3 and 6.6MHz). The external clock can be between 1 to 20MHz with a 45 to 55% duty cycle.
 * I'm currently using the a clock generated by a timer peripheral at 20MHz.
 *
 * MCP3564_USE_EXT_VREF: the internal voltage reference is specified to be 2.4V +/- 2%, so some designs will
 * want to use an external voltage reference.
 *
 * MCP3564_USE_CONV_COMPLETE_INT: the ADC will pull its interrupt pin low when a conversion is complete. This
 * can be used to wake our task which can then read the value. This lowers our SPI traffic as we don't have to
 * poll the STATUS byte waiting for the DR_STATUS bit to go low.
 *
 * MCP3564_ENABLE_AUTOZERO_ALGO: this setting multiplies the conversion time by two. Continuous conversion will
 * not work and instead the ADC will do consecutive one-shot conversions.
 *
 * Approximate numbers from testing with scope, measuring time between data ready interrupts, with a 16MHz
 * external clock:
 *
 *   MUX mode (repeated one-shot conversions, cycling through channels by selecting them in MUX register)
 *
 *   - WITHOUT autozero mux setting on: approx. 0.880ms
 *   - WITH    autozero mux setting on: approx. 1.566ms
 *
 *   SCAN mode (continuous conversion, setting up SCAN register once and receiving an interrupt when each
 *   channel value is ready)
 *
 *   - WITHOUT autozero mux setting on: approx. 0.660ms
 *   - WITH    autozero mux setting on: approx. 1.320ms
 *
 * In tests on hand-built prototype shields, it did not appear that this setting significantly improved the
 * accuracy of our voltage readings. However, the hand-built boards have a lot of long wires so a well-designed
 * PCB would likely couple less noise onto the input pins.
 */
#define MCP3564_USE_EXT_CLOCK         1
#define MCP3564_USE_EXT_VREF          0
#define MCP3564_USE_CONV_COMPLETE_INT 1
#define MCP3564_ENABLE_AUTOZERO_ALGO  0

/*
 * Build-time setting to determine if we use MUX or SCAN mode. In both cases, the code reads all channels for
 * testing purposes.
 */
#define MCP3564_USE_MUX_MODE          1
#define MCP3564_USE_SCAN_MODE         2
#define MCP3564_USE_MODE              MCP3564_USE_SCAN_MODE

/*
 * For the mux and scan test modes above, we can configure the commands to read the inputs single-ended or
 * double-ended.
 */
#define MCP3564_INPUTS_SE             1
#define MCP3564_INPUTS_DE             2
#define MCP3564_INPUTS_TYPE           MCP3564_INPUTS_SE

/*
 * Allow some measurement of the difference between using HAL interrupt transfers and HAL DMA transfers.
 * Our ADC uses only very small transfers and the wall clock time overhead of using a DMA engine for each
 * one may not be worth the CPU time savings.
 */
#define MCP3564_USE_HAL_SPI_INT_MODE  1
#define MCP3564_USE_HAL_SPI_DMA_MODE  2
#define MCP3564_HAL_SPI_MODE          MCP3564_USE_HAL_SPI_INT_MODE

/*
 * Turn this on if we want to capture counts of each channel read so we can pause the running code and examine
 * the counts. The counts can tell us whether the channels are all being read as expected in round-robin order.
 * We expect transfers that have completed in the current cycle will have counts that are 1 higher than the
 * transfers that haven't been executed yet, but if there are other variations in the counts, this indicates that
 * we have failed to get and handle all the interrupts or DMA transfers and have dropped some samples.
 */
#define MCP3564_DBG_COUNT_CHAN_READS  1

#endif /* ADC_MCP3564R_CONFIG_H_ */
